### ISSUE TITLE
Can't resolve 'viz.js' in 'C:\Users\alexa\ae2\node_modules\graphql-voyager\dist'

### ISSUE THREAD

**Issue by barbalex** [APIs-guru/graphql-voyager#88] opened 2018-09-26 14:02 UTC
I have tried  a bunch of stuff to prevent this error:

- reverting to graphql-voyager 1.0.0-rc.19
- installing graphql in versions 14.0.0 or 14.0.2
- using yarn's resolution feature in package.json to force all graphql versions to use v14.0.0 or v14.0.2
- cleaning yarn cache
- deleting node_modules, reinstalling all dependencies

But no matter what, this error results:

```
./node_modules/graphql-voyager/dist/voyager.lib.js
Module not found: Can't resolve 'viz.js' in 'C:\Users\alexa\ae2\node_modules\graphql-voyager\dist'
function.console.(anonymous function) @ index.js:1
handleErrors @ webpackHotDevClient.js:178
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:211
push../node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
push../node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:276
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
```

Some info:

- Windows 10
- Chrome 69.0.3497.100
- graphql-voyager 1.0.0-rc.25
- create-react-app v2

My project:
- package.json: https://github.com/FNSKtZH/ae2/blob/a1596bd7dcd93e0e51192730c0315141e5ead00b/package.json
- worker file: https://github.com/FNSKtZH/ae2/blob/a1596bd7dcd93e0e51192730c0315141e5ead00b/public/voyager.worker.js
- the component itself: https://github.com/FNSKtZH/ae2/tree/a1596bd7dcd93e0e51192730c0315141e5ead00b/src/components/DataGraph

**Comment by RomanGotsiy** [comment] 2018-09-27 07:43
@barbalex could you provide some more details on how to reproduce it?

I just cloned your repo, did `npm install` and then `npm start` both on MacOS and Windows 10 machine and can't see any errors in the terminal.
The site is also opened (although it doesn't show anything as I can't start graphql server)

**Comment by barbalex** [comment] 2018-09-27 07:53
@RomanGotsiy Yeah, you could not reproduce it because I removed graphql-voyager to get my project working again. You should `git checkout a1596bd7dcd93e0e51192730c0315141e5ead00b`

**Comment by RomanGotsiy** [comment] 2018-09-27 09:05
Thanks for the info.

The is caused by absence `viz.js` in dependencies.
The issue is fixed now and will land in the upcoming release.

As a temporary workaround run:

```
npm i viz.js --save
```

**Closed** 2018-09-27 09:05 UTC
Labels: bug
