### ISSUE TITLE
Cannot find module 'koa'.

### ISSUE THREAD

**Issue by anodynos** [APIs-guru/graphql-voyager#87] opened 2018-09-23 21:19 UTC
When importing as mentioned in docs for an express project:

    import { express as voyagerMiddleware } from 'graphql-voyager/middleware';

I get 

     node_modules/graphql-voyager/middleware/koa.d.ts:1:25 - error TS2307: Cannot find module 'koa'.

     1 import { Context } from 'koa';

from `typescript@2.9.2`

**Comment by daniloferreira** [comment] 2018-09-28 11:33
I realized how make it work:
`
import voyagerMiddleware =  require('graphql-voyager/middleware/express');
app.use('/voyager', voyagerMiddleware.default({ endpointUrl: '/graphql' }));
`

**Comment by daniloferreira** [comment] 2018-09-28 11:45
this way worked better:
`
import voyagerMiddleware from  'graphql-voyager/middleware/express';
app.use('/voyager', voyagerMiddleware({ endpointUrl: '/graphql' }));
`

**Comment by IvanGoncharov** [comment] 2018-10-01 13:13
@anodynos @daniloferreira Just published `1.0.0-rc.26` 📦 with a fix included. Can you please try.

> this way worked better:
import voyagerMiddleware from 'graphql-voyager/middleware/express'; app.use('/voyager', voyagerMiddleware({ endpointUrl: '/graphql' }));

@daniloferreira It's workaround not a full fix since express middlaware still depends on `@types/express`. So I just removed all externall types from middlewares to completely solve this problem.

**Comment by Apollinaire** [comment] 2018-10-03 16:54
@IvanGoncharov I get `TypeError: voyagerMiddleware is not a function` with the following imports on ` 1.0.0-rc.26` : 
```js
import { express as voyagerMiddleware } from 'graphql-voyager/middleware';  // => undefined
//or
import voyagerMiddleware  from 'graphql-voyager/middleware/express'; // => { }
```

**Comment by IvanGoncharov** [comment] 2018-10-03 19:39
@Apollinaire Strange, it works for me when I'm doing:
```js
const { express: voyagerMiddleware } = require('graphql-voyager/middleware');
```
Can you please test the same code in your setup.
I see you are using ES6 modules, what environment do you using `babel`, `typescript`, `esm`?

**Comment by Apollinaire** [comment] 2018-10-04 09:59
I'm using Meteor to build, with the [`ecmascript`](https://docs.meteor.com/packages/ecmascript.html) package, which uses Babel under the hood. To be more precise, i'm trying to include this to  vulcan.js : https://github.com/vulcanjs/vulcan 
Any import on server side returns undefined. On the client it works, but I need the middleware to run serverside only, because that's where I create my express app.

**Comment by IvanGoncharov** [comment] 2018-10-04 10:28
@Apollinaire I'm not familiar with meteor so can you please create GitHub repo with the minimal setup to reproduce this issue?

**Comment by Apollinaire** [comment] 2018-10-04 14:48
After further search, it seems related to how I build my project. Something in my config must be wrong because I am able to import and run the middleware in other Vulcan/Meteor projects. 
I'll update this when I've found the issue, it might be useful for future people

**Comment by IvanGoncharov** [comment] 2018-10-04 17:42
@Apollinaire I'm closing this issue since the original issue was resolved.
But please post your findings here it will help if other Meteor users will have the same problem.

**Closed by IvanGoncharov** 2018-10-04 17:42 UTC

**Comment by Apollinaire** [comment] 2018-10-05 09:17
@IvanGoncharov it was just some bad config from me, other should not have the same problem.

**Comment by Apollinaire** [comment] 2019-01-03 15:17
@SachaG If I remember well the problem was that I was doing `npm i --save-dev graphql-voyager` because I was thinking that I only had to use it on dev environment. But Meteor did not like this, so I just did `npm i graphql-voyager` and it worked !

**Comment by SachaG** [comment] 2019-01-04 10:41
Haha exact same issue for me! Thanks!

**Comment by eric-burel** [comment] 2019-01-30 16:55
Guess who got the same issue

**Comment by Apollinaire** [comment] 2019-01-31 09:00
> Haha exact same issue for me! Thanks!

> Guess who got the same issue

We're one damn fine core team for Vulcan.js
