### ISSUE TITLE
Clicking on type in Firefox

### ISSUE THREAD

**Issue by LaurenceGA** [APIs-guru/graphql-voyager#80] opened 2018-07-26 20:50 UTC
In Firefox, if you click on a type in the sidebar or in the graph, instead of centring the view on the type, it centres somewhere off near the start of the graph.

**Comment by IvanGoncharov** [comment] 2018-07-26 21:05
@LaurenceGA Do you use our online demo or NPM package?

**Comment by LaurenceGA** [comment] 2018-07-26 22:56
npm package. Live demo seems to work fine.

**Comment by IvanGoncharov** [comment] 2018-07-27 10:41
@RomanGotsiy I suspect it's duplicate of #76 which already have reproduce sample.

**Comment by LaurenceGA** [comment] 2018-07-27 11:06
Hmm yes, may be a duplicate actually.
Yeah I can try throw a sample together sometime this weekend. There's nothing special in the project it's in.
For some extra detail, the bug was found on latest Firefox on the latest Mac OSX (no bug with latest chrome on the same machine).

**Comment by IvanGoncharov** [comment] 2019-04-19 12:39
@LaurenceGA Sorry for the delay.
Fixed in `1.0.0-rc.26`

**Closed by IvanGoncharov** 2019-04-19 12:39 UTC
